# Azure Pipeline that run basic continuous integration on a Terraform project

# This makes sure the pipeline is triggered every time code is pushed on all branches.
trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - 'lab-1-terraform-resources/terraform/*'

variables:
  # There must be an Azure Service Connection with that name defined in your Azure DevOps settings. See https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops
  serviceConnection: ''
  azureLocation: ''
  # Terraform settings
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/lab-1-terraform-resources/terraform/*'
  terraformVersion: '0.12.25'
pool:
  vmImage: ubuntu-latest
steps:
- script: |
      docker run -t -v $(terraformWorkingDirectory):/tf bridgecrew/checkov --directory /tf
  name: 'Terraform Static Code Analysis using Checkov'
