name: Terraform Security Checks
on:
  push:
    paths:
    - lab-1-terraform-resources/terraform
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: lab-1-terraform-resources/terraform/resource-group
          soft_fail: true 
          framework: terraform
          output_format: github_failed_only
          download_external_modules: true
          log_level: WARNING 
