name: Terraform Security Checks
on:
  push:
    paths:
      - 'lab-1-terraform-resources/terraform/resource-group/**'

jobs:
  checkov-job:
    name: Terraform Security Scanning with Checkov
    defaults:
      run:
        working-directory: lab-1-terraform-resources/terraform/resource-group
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov Scanning 
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: lab-1-terraform-resources/terraform/resource-group
          soft_fail: true 
          framework: terraform
          output_format: github_failed_only
          download_external_modules: true
          log_level: WARNING 
