name: Terraform Compliance Checks
on:
  push:
    paths:
      - 'lab-1-terraform-resources/terraform/resource-group/**'
jobs:
    compliance-test:
      defaults:
        run:
          working-directory: lab-1-terraform-resources/terraform/resource-group
      runs-on: ubuntu-latest
      name: Terraform Compliance Testing
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      steps:
        - name: 'Checkout'
          uses: actions/checkout@master
        - uses: hashicorp/setup-terraform@v1
        # Check for formatting
      - name: Generating Terraform Plan
        id: plan
        run: |
          terraform init && terraform plan -out=plan.out && terraform show -json plan.out > plan.out.json
      - name: Checking Plan for Compliance
        uses: terraform-compliance/github_action@main
        with:
          plan: plan.out.json
          features: ssh://git@github.com/terraform-compliance/user-friendly-features.git
