name: Terraform Compliance Checks
on:
  push:
    paths:
    - "**.tf"
    - ".github/workflows/terraform-compliance-actions.yml"
jobs:
  
  test:
      runs-on: ubuntu-latest
      name: Terraform Compliance Testing
      env:
        ARM_CLIENT_ID: <client-id>
        ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
        ARM_SUBSCRIPTION_ID: <subscription-id>
        ARM_TENANT_ID: <tenant-id>
      steps:
        - uses: actions/checkout@v2
        - uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 0.14.x
        - uses: terraform-compliance/github_action@main
        # Check for formatting
        - name: formatting check
          run: terraform fmt --check     
        - name: Terraform Init 
          id: init
          run: terraform init
        - name: terraform plan
          id: plan
          run: |
            terraform init && terraform plan -out=plan.out && terraform show -json plan.out > plan.out.json
        - name: terraform-compliance
          uses: terraform-compliance/github_action@main
          with:
            plan: plan.out.json
            features: lab-1-terraform-resources/terraform/compliance
